[package]
name = 'run_script'
version = '1.0.0'

[addresses]
test_addr = "_"

[dependencies.LumioFramework]
git = 'ssh://git@github.com/pontem-network/lumio-node.git'
rev = 'mainnet'
subdir = 'lumio-move/framework/lumio-framework'

[dependencies.LumioTokenObjects]
git = 'ssh://git@github.com/pontem-network/lumio-node.git'
rev = 'mainnet'
subdir = 'lumio-move/framework/lumio-token-objects'

[dependencies.MoveStdlib]
git = 'ssh://git@github.com/pontem-network/lumio-node.git'
rev = 'mainnet'
subdir = 'lumio-move/framework/move-stdlib'

[dependencies.LumioToken]
git = 'ssh://git@github.com/pontem-network/lumio-node.git'
rev = 'mainnet'
subdir = 'lumio-move/framework/lumio-token'
